<?php

declare(strict_types=1);

return [
    'classes' => [
        'official_federal' => 'Федеральный официальный источник',
        'official_regional' => 'Региональный официальный источник',
        'state_company' => 'Государственная компания',
        'federal_media' => 'Федеральное СМИ',
        'business_media' => 'Деловое СМИ',
        'industry_media' => 'Отраслевое СМИ',
    ],

    /*
     * Каталог из согласованного макета раздела «Источники».
     * Для проверенных RSS/Atom-лент здесь также указаны feed_url и тематики.
     * Остальные сайты показываются в каталоге без запуска мониторинга.
     */
    'sources' => [
        ['name' => 'Официальное опубликование правовых актов', 'domain' => 'publication.pravo.gov.ru', 'source_class' => 'official_federal', 'trust_score' => 100, 'poll_interval_minutes' => 30],
        ['name' => 'Росстат', 'domain' => 'rosstat.gov.ru', 'source_class' => 'official_federal', 'trust_score' => 100, 'poll_interval_minutes' => 30],
        ['name' => 'Росреестр', 'domain' => 'rosreestr.gov.ru', 'source_class' => 'official_federal', 'trust_score' => 100, 'poll_interval_minutes' => 30],
        [
            'name' => 'Росавтодор',
            'domain' => 'rosavtodor.gov.ru',
            'source_class' => 'official_federal',
            'trust_score' => 100,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://rosavtodor.gov.ru/rss',
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
            ],
        ],
        [
            'name' => 'Минтранс России',
            'domain' => 'mintrans.gov.ru',
            'source_class' => 'official_federal',
            'trust_score' => 100,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'http://government.ru/department/68/events/rss/',
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
            ],
        ],
        [
            'name' => 'Минстрой России',
            'domain' => 'minstroyrf.gov.ru',
            'source_class' => 'official_federal',
            'trust_score' => 100,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://minstroyrf.gov.ru/bitrix/rss.php?ID=2&LIMIT=50',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'architecture',
                'building_materials',
                'government_programs',
            ],
        ],
        [
            'name' => 'Правительство России',
            'domain' => 'government.ru',
            'source_class' => 'official_federal',
            'trust_score' => 100,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'http://government.ru/all/rss/',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        [
            'name' => 'Минстрой Московской области',
            'domain' => 'msk.mosreg.ru',
            'legacy_domains' => ['minstroy.mosreg.ru'],
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://msk.mosreg.ru/sobytiya/novosti-ministerstva?format=rss',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'government_programs',
            ],
        ],
        [
            'name' => 'Правительство Москвы',
            'domain' => 'mos.ru',
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'is_active' => false,
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'architecture',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        [
            'name' => 'Стройкомплекс Москвы',
            'domain' => 'stroi.mos.ru',
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://stroi.mos.ru/news/rss',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'architecture',
                'building_materials',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        [
            'name' => 'Транспорт Москвы',
            'domain' => 'transport.mos.ru',
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'is_active' => false,
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
            ],
        ],
        [
            'name' => 'Минтранс Московской области',
            'domain' => 'mtdi.mosreg.ru',
            'legacy_domains' => ['mostrans.gov.ru'],
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://mtdi.mosreg.ru/sobytiya/novosti-ministerstva?format=rss',
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
            ],
        ],
        [
            'name' => 'Правительство Санкт-Петербурга',
            'domain' => 'gov.spb.ru',
            'source_class' => 'official_regional',
            'trust_score' => 95,
            'poll_interval_minutes' => 30,
            'type' => 'rss',
            'feed_url' => 'https://www.gov.spb.ru/news/rss/',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'architecture',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        ['name' => 'Росатом', 'domain' => 'rosatom.ru', 'source_class' => 'state_company', 'trust_score' => 90, 'poll_interval_minutes' => 60],
        ['name' => 'Интерфакс', 'domain' => 'interfax.ru', 'source_class' => 'federal_media', 'trust_score' => 90, 'poll_interval_minutes' => 60],
        ['name' => 'Ростех', 'domain' => 'rostec.ru', 'source_class' => 'state_company', 'trust_score' => 90, 'poll_interval_minutes' => 60],
        [
            'name' => 'ВЭБ.РФ',
            'domain' => 'veb.ru',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'type' => 'rss',
            'feed_url' => 'https://veb.ru/rss/',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        [
            'name' => 'РЖД',
            'domain' => 'company.rzd.ru',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'is_active' => false,
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
                'industrial_construction',
            ],
        ],
        [
            'name' => 'Автодор',
            'domain' => 'russianhighways.ru',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'is_active' => false,
            'categories' => [
                'construction',
                'infrastructure',
                'government_programs',
                'transport_infrastructure',
            ],
        ],
        [
            'name' => 'Строим.ДОМ.РФ',
            'domain' => 'строим.дом.рф',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'is_active' => false,
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'architecture',
                'building_materials',
                'government_programs',
            ],
        ],
        [
            'name' => 'Наш.ДОМ.РФ',
            'domain' => 'наш.дом.рф',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'is_active' => false,
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'government_programs',
            ],
        ],
        [
            'name' => 'ДОМ.РФ',
            'domain' => 'дом.рф',
            'source_class' => 'state_company',
            'trust_score' => 90,
            'poll_interval_minutes' => 60,
            'type' => 'rss',
            'feed_url' => 'https://xn--d1aqf.xn--p1ai/media/news/rss/',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'architecture',
                'government_programs',
            ],
        ],
        ['name' => 'РИА Новости', 'domain' => 'ria.ru', 'source_class' => 'federal_media', 'trust_score' => 90, 'poll_interval_minutes' => 60],
        ['name' => 'ТАСС', 'domain' => 'tass.ru', 'source_class' => 'federal_media', 'trust_score' => 90, 'poll_interval_minutes' => 60],
        ['name' => 'Российская газета', 'domain' => 'rg.ru', 'source_class' => 'business_media', 'trust_score' => 85, 'poll_interval_minutes' => 60],
        ['name' => 'Ведомости', 'domain' => 'vedomosti.ru', 'source_class' => 'business_media', 'trust_score' => 85, 'poll_interval_minutes' => 60],
        [
            'name' => 'РБК Недвижимость',
            'domain' => 'realty.rbc.ru',
            'source_class' => 'business_media',
            'trust_score' => 85,
            'poll_interval_minutes' => 60,
            'type' => 'rss',
            'feed_url' => 'https://rssexport.rbc.ru/realty/news/30/full.rss',
            'categories' => [
                'construction',
                'development',
                'infrastructure',
                'real_estate',
                'housing_utilities',
                'architecture',
                'building_materials',
                'government_programs',
            ],
        ],
        ['name' => 'РБК', 'domain' => 'rbc.ru', 'source_class' => 'business_media', 'trust_score' => 85, 'poll_interval_minutes' => 60],
        ['name' => 'Коммерсантъ', 'domain' => 'kommersant.ru', 'source_class' => 'business_media', 'trust_score' => 85, 'poll_interval_minutes' => 60],
        ['name' => 'ЕРЗ.РФ', 'domain' => 'erzrf.ru', 'source_class' => 'industry_media', 'trust_score' => 70, 'poll_interval_minutes' => 60],
    ],
];
